//==================================================
//     Outputs that match the input variables
//==================================================
output "certificate_authority" {
  description = "The value of the `certificate_authority` input variable, or the default value if the input was `null`."
  value       = var.certificate_authority
}
output "acm_import" {
  description = "The value of the `acm_import` input variable, or the default value if the input was `null`."
  value       = var.acm_import
}
output "key_algorithm" {
  description = "The value of the `key_algorithm` input variable, or the default value if the input was `null`."
  value       = var.key_algorithm
}
output "ecdsa_curve" {
  description = "The value of the `ecdsa_curve` input variable, or the default value if the input was `null`."
  value       = var.ecdsa_curve
}
output "key_bits" {
  description = "The value of the `key_bits` input variable, or the default value if the input was `null`."
  value       = var.key_bits
}
output "certificate_acm_name" {
  description = "The value of the `certificate_acm_name` input variable, or the default value if the input was `null`."
  value       = var.certificate_acm_name
}
output "subject_common_name" {
  description = "The value of the `subject_common_name` input variable."
  value       = var.subject_common_name
}
output "subject_organization" {
  description = "The value of the `subject_organization` input variable, or the default value if the input was `null`."
  value       = var.subject_organization
}
output "subject_organizational_unit" {
  description = "The value of the `subject_organizational_unit` input variable, or the default value if the input was `null`."
  value       = var.subject_organizational_unit
}
output "subject_street_address" {
  description = "The value of the `subject_street_address` input variable, or the default value if the input was `null`."
  value       = var.subject_street_address
}
output "subject_locality" {
  description = "The value of the `subject_locality` input variable, or the default value if the input was `null`."
  value       = var.subject_locality
}
output "subject_province" {
  description = "The value of the `subject_province` input variable, or the default value if the input was `null`."
  value       = var.subject_province
}
output "subject_country" {
  description = "The value of the `subject_country` input variable, or the default value if the input was `null`."
  value       = var.subject_country
}
output "subject_postal_code" {
  description = "The value of the `subject_postal_code` input variable, or the default value if the input was `null`."
  value       = var.subject_postal_code
}
output "subject_serial_number" {
  description = "The value of the `subject_serial_number` input variable, or the default value if the input was `null`."
  value       = var.subject_serial_number
}
output "validity_period_hours" {
  description = "The value of the `validity_period_hours` input variable, or the default value if the input was `null`."
  value       = var.validity_period_hours
}
output "dns_names" {
  description = "The value of the `dns_names` input variable, or the default value if the input was `null`."
  value       = var.dns_names
}
output "ip_addresses" {
  description = "The value of the `ip_addresses` input variable, or the default value if the input was `null`."
  value       = var.ip_addresses
}
output "uris" {
  description = "The value of the `uris` input variable, or the default value if the input was `null`."
  value       = var.uris
}
output "early_renewal_hours" {
  description = "The value of the `early_renewal_hours` input variable, or the default value if the input was `null`."
  value       = var.early_renewal_hours
}
output "is_ca_certificate" {
  description = "The value of the `is_ca_certificate` input variable, or the default value if the input was `null`."
  value       = var.is_ca_certificate
}
output "set_subject_key_id" {
  description = "The value of the `set_subject_key_id` input variable, or the default value if the input was `null`."
  value       = var.set_subject_key_id
}
output "allowed_uses" {
  description = "The value of the `allowed_uses` input variable, or the default value if the input was `null`."
  value       = var.allowed_uses
}


//==================================================
//       Outputs generated by this module
//==================================================
output "certificate" {
  description = "The ACM certificate that was imported. Value will be null unless the 'acm_import' variable was set to 'true'."
  value       = var.acm_import ? aws_acm_certificate.cert[0] : null
}

output "private_key_pem" {
  description = "The PEM-encoded private key for the certificate."
  value       = tls_private_key.key.private_key_pem
}

output "certificate_pem" {
  description = "The PEM-encoded signed certificate."
  value       = local.cert_pem
}
